export const environment = {
  production: true,
  name: "prod",
  subDomainName: "",
  emrUrl: "https://emr.clenicapp.com/",
  baseUrl: "",
  pcareUrl: "",
  socketUrl: "http://sockettabaro.clenic.id/",
  satuSehatUrl: "https://satusehat.clenicapp.com/api/",
  rawatJalanUrl: "",
  apiPath: "api/",
  masterPath: "master/",
  pcareMcuPath: "/pcare/mcu",
  pcareObatPath: "/pcare/obat",
  pcareKelompokPath: "/pcare/kelompok",
  cabangPath: "api/master-data/cabang/",
  rawatJalanPath: "/asesmen-rawat-jalan",
  antrianFktpPath: "/antrean-fktp/bpjs/",
  version: 'v4.0.0'
};