name: Build & Deploy workflow

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Ambil list branches dari API & generate matrix
        id: set-matrix
        run: |
          echo "Fetching branches…"
          json=$(curl -s https://emr.clenicapp.com/api/get-branches)
          matrix=$(echo "$json" | jq -c '.data')
          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install --legacy-peer-deps --no-audit --no-fund

      - name: Build app
        run: npm run build -- --configuration production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./dist/clenicappdemo/
          retention-days: 1

  deploy:
    needs: [build, generate-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: "${{ fromJson(needs.generate-matrix.outputs.matrix) }}"

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./dist/clenicappdemo/

      - name: FTP Deploy to ${{ matrix.folder }}
        uses: SamKirkland/FTP-Deploy-Action@v4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          protocol: ftp
          local-dir: ./dist/clenicappdemo/
          server-dir: /${{ matrix.folder }}.clenicapp.com/v1/
