name: Build & Deploy workflow

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Ambil list branches dari API & generate matrix
        id: set-matrix
        run: |
          echo "Fetching branches…"
          json=$(curl -s https://emr.clenicapp.com/api/get-branches)
          matrix=$(echo "$json" | jq -c '.data')
          echo "Matrix: $matrix"
          echo "matrix=$matrix" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "12"

      - name: Cache NPM
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build --production

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ./dist/clenicappdemo/

  deploy:
    needs: [build, generate-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder: "${{ fromJson(needs.generate-matrix.outputs.matrix) }}"

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: ./dist/clenicappdemo/

      - name: SFTP Deploy to tabaro
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }} # default 22 jika tidak diisi
          SOURCE: "./dist/clenicappdemo/"
          TARGET: "/home/your_user/tabaro.clenicapp.com/v1-test/"
          ARGS: "-avz --delete"
